root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - eslint-config-prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - './tsconfig.json'
settings:
  react:
    version: detect
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - tss-unused-classes
rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
      ignoreRestSiblings: true
  '@typescript-eslint/no-unnecessary-condition': warn
  tss-unused-classes/unused-classes: warn
  import/order:
    - warn
    - groups:
        - builtin
        - external
        - internal
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      warnOnUnassignedImports: true
  max-len:
    - warn
    - 120
    - 2
  no-console:
    - warn
    - allow:
        - error
        - warning
        - info
  semi:
    - error
    - always
  quotes:
    - error
    - single
    - avoidEscape: true
  prefer-template: error
  no-useless-concat: error
